<div style="text-align: center; font-size: 24px;">
  <span style="color: red; font-weight: bold;">[ 퀴즈 1]</span><br>
  <span style="color: orange; font-weight: bold;">아래와 같은 결과를 만들기 위해 빈 칸에 알맞은 코드를 작성하시오.</span><br>
  <span style="font-weight: bold;">(주어진 데이터에서 KBS의 시청률이 30이 넘은 데이터만 확인)</span>
</div>

In [1]:
import pandas as pd

df = pd.read_csv('broadcast.csv', index_col=0)
df

         KBS     MBC     SBS  TV CHOSUN   JTBC  Channel A    MBN
2011  35.951  18.374  11.173      9.102  7.380      3.771  2.809
2012  36.163  16.022  11.408      8.785  7.878      5.874  3.310
2013  31.989  16.778   9.673      9.026  7.810      5.350  3.825
2014  31.210  15.663   9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573   9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982   8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465   8.661      8.886  9.453      6.056  5.215

In [2]:
df['KBS'] > 30 # KBS 에서 시청률이 30보다 큰 값 검색 - Series

2011     True
2012     True
2013     True
2014     True
2015    False
2016    False
2017    False
Name: KBS, dtype: bool

In [8]:
df.loc[df['KBS'] > 30, 'KBS'] # KBS 에서 시청률이 30보다 큰 값 검색(인덱싱) - Series

2011    35.951
2012    36.163
2013    31.989
2014    31.210
Name: KBS, dtype: float64

In [3]:
df.loc[df['KBS'] > 30, ['KBS']] # KBS 에서 시청률이 30보다 큰 값 검색(인덱싱) - DataFrame

         KBS
2011  35.951
2012  36.163
2013  31.989
2014  31.210

In [4]:
df[['KBS']].loc[df['KBS'] > 30] # KBS 에서 시청률이 30보다 큰 값 검색 - DataFrame (loc 즉 로케이션 명령어 없는 버전) (같은 결과지만 처리 속도가 빠름)

         KBS
2011  35.951
2012  36.163
2013  31.989
2014  31.210

# **[20260421 Tue] - 오늘 수업 종료(2교시).**

# **[20260422 Wed] - 오늘 수업 시작(5교시).**

<div style="text-align: center; font-size: 24px;">
  <span style="color: red; font-weight: bold;">[ 퀴즈 2]</span><br>
  <span style="color: orange; font-weight: bold;">아래와 같은 결과를 만들기 위해 빈 칸에 알맞은 코드를 작성하시오.</span><br>
  <span style="font-weight: bold;">주어진 데이터에서 SBS가 TV CHOSUN보다 더 시청률이 낮았던 시기의 데이터를 확인</span>
</div>

In [1]:
import pandas as pd

df = pd.read_csv('broadcast.csv', index_col=0)
df

         KBS     MBC     SBS  TV CHOSUN   JTBC  Channel A    MBN
2011  35.951  18.374  11.173      9.102  7.380      3.771  2.809
2012  36.163  16.022  11.408      8.785  7.878      5.874  3.310
2013  31.989  16.778   9.673      9.026  7.810      5.350  3.825
2014  31.210  15.663   9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573   9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982   8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465   8.661      8.886  9.453      6.056  5.215

In [4]:
df['SBS'] > 10 # SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Series

2011     True
2012     True
2013    False
2014    False
2015    False
2016    False
2017    False
Name: SBS, dtype: bool

In [5]:
# SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Series
# 코드 공석

In [6]:
# SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Dataframe
# 코드 공석

In [8]:
df.loc[df['SBS'] > 30, 'TV CHOSUN'] # ?

Series([], Name: TV CHOSUN, dtype: float64)

### **정정 코드?** (챗GPT)

In [9]:
df['SBS'][df['SBS'] < df['TV CHOSUN']]

2014    9.108
2015    9.099
2016    8.669
2017    8.661
Name: SBS, dtype: float64

In [10]:
df[df['SBS'] < df['TV CHOSUN']]

         KBS     MBC    SBS  TV CHOSUN   JTBC  Channel A    MBN
2014  31.210  15.663  9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573  9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982  8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465  8.661      8.886  9.453      6.056  5.215

#### **뽀너스**) (인덱스까지 뽑고 싶으면)

In [11]:
df.index[df['SBS'] < df['TV CHOSUN']]

Index([2014, 2015, 2016, 2017], dtype='int64')

### 여기서부터 다시 **Teacher**