<div style="text-align: center; font-size: 24px;">
  <span style="color: red; font-weight: bold;">[ 퀴즈 1]</span><br>
  <span style="color: orange; font-weight: bold;">아래와 같은 결과를 만들기 위해 빈 칸에 알맞은 코드를 작성하시오.</span><br>
  <span style="font-weight: bold;">(주어진 데이터에서 KBS의 시청률이 30이 넘은 데이터만 확인)</span>
</div>

In [1]:
import pandas as pd

df = pd.read_csv('broadcast.csv', index_col=0)
df

         KBS     MBC     SBS  TV CHOSUN   JTBC  Channel A    MBN
2011  35.951  18.374  11.173      9.102  7.380      3.771  2.809
2012  36.163  16.022  11.408      8.785  7.878      5.874  3.310
2013  31.989  16.778   9.673      9.026  7.810      5.350  3.825
2014  31.210  15.663   9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573   9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982   8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465   8.661      8.886  9.453      6.056  5.215

In [2]:
df['KBS'] > 30 # KBS 에서 시청률이 30보다 큰 값 검색 - Series

2011     True
2012     True
2013     True
2014     True
2015    False
2016    False
2017    False
Name: KBS, dtype: bool

In [8]:
df.loc[df['KBS'] > 30, 'KBS'] # KBS 에서 시청률이 30보다 큰 값 검색(인덱싱) - Series

2011    35.951
2012    36.163
2013    31.989
2014    31.210
Name: KBS, dtype: float64

In [3]:
df.loc[df['KBS'] > 30, ['KBS']] # KBS 에서 시청률이 30보다 큰 값 검색(인덱싱) - DataFrame

         KBS
2011  35.951
2012  36.163
2013  31.989
2014  31.210

In [4]:
df[['KBS']].loc[df['KBS'] > 30] # KBS 에서 시청률이 30보다 큰 값 검색 - DataFrame (loc 즉 로케이션 명령어 없는 버전) (같은 결과지만 처리 속도가 빠름)

         KBS
2011  35.951
2012  36.163
2013  31.989
2014  31.210

# **[20260421 Tue] - 오늘 수업 종료(2교시).**

# **[20260422 Wed] - 오늘 수업 시작(5교시).**

<div style="text-align: center; font-size: 24px;">
  <span style="color: red; font-weight: bold;">[ 퀴즈 2]</span><br>
  <span style="color: orange; font-weight: bold;">아래와 같은 결과를 만들기 위해 빈 칸에 알맞은 코드를 작성하시오.</span><br>
  <span style="font-weight: bold;">주어진 데이터에서 SBS가 TV CHOSUN보다 더 시청률이 낮았던 시기의 데이터를 확인</span>
</div>

In [1]:
import pandas as pd

df = pd.read_csv('broadcast.csv', index_col=0)
df

         KBS     MBC     SBS  TV CHOSUN   JTBC  Channel A    MBN
2011  35.951  18.374  11.173      9.102  7.380      3.771  2.809
2012  36.163  16.022  11.408      8.785  7.878      5.874  3.310
2013  31.989  16.778   9.673      9.026  7.810      5.350  3.825
2014  31.210  15.663   9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573   9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982   8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465   8.661      8.886  9.453      6.056  5.215

In [4]:
df['SBS'] > 10 # SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Series

2011     True
2012     True
2013    False
2014    False
2015    False
2016    False
2017    False
Name: SBS, dtype: bool

In [5]:
# SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Series
# 코드 공석

In [6]:
# SBS가 TV CHOSUN보다 시청률이 낮은 값 검색 - Dataframe
# 코드 공석

In [8]:
df.loc[df['SBS'] > 30, 'TV CHOSUN'] # ?

Series([], Name: TV CHOSUN, dtype: float64)

### **정정 코드?** (챗GPT)

In [9]:
df['SBS'][df['SBS'] < df['TV CHOSUN']]

2014    9.108
2015    9.099
2016    8.669
2017    8.661
Name: SBS, dtype: float64

In [10]:
df[df['SBS'] < df['TV CHOSUN']]

         KBS     MBC    SBS  TV CHOSUN   JTBC  Channel A    MBN
2014  31.210  15.663  9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573  9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982  8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465  8.661      8.886  9.453      6.056  5.215

#### **뽀너스**) (인덱스까지 뽑고 싶으면)

In [11]:
df.index[df['SBS'] < df['TV CHOSUN']]

Index([2014, 2015, 2016, 2017], dtype='int64')

### 여기서부터 다시 **Teacher**

In [12]:
# SBS 시청률
df['SBS']

2011    11.173
2012    11.408
2013     9.673
2014     9.108
2015     9.099
2016     8.669
2017     8.661
Name: SBS, dtype: float64

In [13]:
# 두 방송사 시청률 비교하는 조건식 만들기
df['SBS'] < df['TV CHOSUN']

2011    False
2012    False
2013    False
2014     True
2015     True
2016     True
2017     True
dtype: bool

In [16]:
# 데이터프레임으로 조건식 반영
df.loc[df['SBS'] < df['TV CHOSUN']]

         KBS     MBC    SBS  TV CHOSUN   JTBC  Channel A    MBN
2014  31.210  15.663  9.108      9.440  7.490      5.776  4.572
2015  27.777  16.573  9.099      9.940  7.267      6.678  5.520
2016  27.583  14.982  8.669      9.829  7.727      6.624  5.477
2017  26.890  12.465  8.661      8.886  9.453      6.056  5.215

In [17]:
# SBS 가 TV CHOSUN 보다 시청률이 낮았던 시기의 두 방송사 시청률(데이터프레임)
df.loc[df['SBS'] < df['TV CHOSUN'], ['SBS', 'TV CHOSUN']]

        SBS  TV CHOSUN
2014  9.108      9.440
2015  9.099      9.940
2016  8.669      9.829
2017  8.661      8.886

# **[20260422 Wed] - 오늘 수업 종료(5교시).**

# **[20260428 Wed] - 오늘 수업 시작(1교시).**

### **csv파일에서 여러가지 값 가져오기(Boolean List)**

In [1]:
import pandas as pd

In [2]:
iphone_df = pd.read_csv('iphone.csv', index_col=0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [3]:
# Boolean List(True, False)를 이용해서 인덱싱하기 - 인덱스의 개수에 주의!

In [4]:
iphone_df.loc[[True, False, True, False, True, False, True]]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
# Boolean List(True, False)를 이용해서 필터링하기 - 컬럼의 개수에 주의!

In [6]:
iphone_df.loc[:, [True, False, True, False, True]]

                      출시일  메모리 Face ID
iPhone 7       2016-09-16  2GB      No
iPhone 7 Plus  2016-09-16  3GB      No
iPhone 8       2017-09-22  2GB      No
iPhone 8 Plus  2017-09-22  3GB      No
iPhone X       2017-11-03  3GB     Yes
iPhone XS      2018-09-21  4GB     Yes
iPhone XS Max  2018-09-21  4GB     Yes

### **실제로 위의 예제와 같이 사용할 일은 극히 적다!**
### **주로 사용하게 되는 상황은...**

### **1. 디스플레이 크기가 5보다 큰 제품 검색**

In [7]:
# 각 제품의 디스플레이 값 조회

In [8]:
iphone_df[['디스플레이']] > 5

               디스플레이
iPhone 7       False
iPhone 7 Plus   True
iPhone 8       False
iPhone 8 Plus   True
iPhone X        True
iPhone XS       True
iPhone XS Max   True

In [12]:
# 11쪽

# 디스플레이 크기가 5보다 큰 제품 조회 - Series

In [10]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [11]:
# 위 결과값의 타입 확인

In [13]:
type(iphone_df['디스플레이']>5)

pandas.core.series.Series

In [14]:
# 디스플레이 크기가 5보다 큰 제품 인덱싱 - DataFrame

In [15]:
iphone_df.loc[iphone_df['디스플레이']>5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [16]:
# 위 결과값의 타입 확인

In [17]:
type(iphone_df.loc[iphone_df['디스플레이']>5])

pandas.core.frame.DataFrame

### **2. Face ID가 되는 기종 검색**

In [18]:
# 각 제품의 Face ID 값 조회

In [19]:
# Face ID가 되는 제품 조회 - Series

In [20]:
iphone_df['Face ID'] == 'Yes'

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: Face ID, dtype: bool

In [21]:
# Face ID가 되는 제품 인덱싱 - DataFrame

In [22]:
iphone_df.loc[iphone_df['Face ID']=='Yes']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [23]:
# 12쪽은 다시 복습 실습해보기 생략. 워크스페이스에 12쪽 내용을 했던 파일이 아마도 분명히 저장되어 있을 것.

In [24]:
# 15쪽 슬라이싱

### **8. Slicing(슬라이싱)의 다양한 활용**

In [25]:
# 1차원 배열 Days 설정

In [1]:
Days = ['월','화','수','목','금','토','일']

In [27]:
# Days의 첫번째 값 가져오기

In [28]:
Days[1]

'화'

In [29]:
Days[0:5]

['월', '화', '수', '목', '금']

In [33]:
Days[:5]

['월', '화', '수', '목', '금']

In [34]:
Days[5:7]

['토', '일']

In [35]:
Days[5:]

['토', '일']

In [37]:
Days[1:1]

[]

In [38]:
Days[1:0]

[]

In [39]:
Days[0:1]

['월']

In [40]:
Days[4:-1]

['금', '토']

In [41]:
Days[1:6:2]

['화', '목', '토']

In [42]:
Days[0:5:2]

['월', '수', '금']

In [49]:
Days[2:7:2]

['수', '금', '일']

In [50]:
Days[2::2]

['수', '금', '일']

In [51]:
Days[0:7:2]

['월', '수', '금', '일']

In [52]:
Days[:7:2]

['월', '수', '금', '일']

In [53]:
Days[::2]

['월', '수', '금', '일']

In [55]:
Days[0:7:1]

['월', '화', '수', '목', '금', '토', '일']

In [56]:
Days[0:7]

['월', '화', '수', '목', '금', '토', '일']

In [57]:
Days[:]

['월', '화', '수', '목', '금', '토', '일']

In [60]:
Days[7:0:-1] # 내려가는

['일', '토', '금', '목', '수', '화']

In [59]:
Days[6:0:-1]

['일', '토', '금', '목', '수', '화']

In [67]:
Days[6:0:-1]

['일', '토', '금', '목', '수', '화']

In [65]:
Days[6::-1]

['일', '토', '금', '목', '수', '화', '월']

In [66]:
Days[::-1]

['일', '토', '금', '목', '수', '화', '월']

# **[20260428 Tue] - 오늘 수업 종료(2교시).**

# **[20260429 Wed] - 오늘 수업 시작(5교시).**

### **데이터프레임 인덱스 수업(p17-18)**

In [2]:
import pandas as pd

In [4]:
iphone_df = pd.read_csv('iphone.csv', index_col = 0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

#### 코드형식 예
```python
iphone_df.loc[인덱스, 컬럼]

In [5]:
iphone_df.loc[['iPhone 8', 'iPhone X']]

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes

In [8]:
iphone_df.iloc[[2, 4]] #컬럼대신 인덱스로

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes